### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by atherdon** [RaffaellaTran/react-native-album-app#1]
.

**Comment by RaffaellaTran** [comment]
Hi Arthur,

thanks for your message.
I took a quick view to the project. I have a few questions: how many hours
per week are required for the project? Are there fixed skype meeting? Which
level of experience is required?

Best regards,

Raffaella



Il giorno gio 2 ago 2018 alle ore 12:59 Arthur Tkachenko <
notifications@github.com> ha scritto:
